# See https://upptime.js.org/docs/configuration for config docs

# git repo stuff
owner: andreijiroh-dev
repo: infra-status

sites:
  - name: Homepage
    url: https://andreijiroh.dev
    slug: site
  - name: Personal API
    url: https://api.andreijiroh.dev/ping
    slug: api
  - name: Digital Garden / Personal Wiki
    url: https://wiki.andreijiroh.dev
    slug: garden
  #- name: golinks
  #  url: https://go.andreijiroh.xyz/api/ping
  - name: Blog (hosted on Nest)
    url: https://blog.andreijiroh.dev
    slug: blog
  - name: GitBook docs (on docs site w/o custom domain/subdirectory)
    url: https://gitbook.andreijiroh.dev
    slug: gitbook
  - name: Nextcloud on Coolify Homelab
    url: https://nextcloud.andreijiroh.dev
    slug: nextcloud
  - name: Coolify Homelab Server
    url: https://coolify.andreijiroh.dev
    slug: coolify

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.andreijiroh.dev
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Andrei Jiroh's InfraOps"
  introTitle: >
    We're actively monitoring ~ajhalili2006's services using GitHub Actions + Issues + Pages,
    [powered by Upptime](https://github.com/upptime/upptime)
  introMessage: |
    If something went down, we'll looking into it behind the scenes and a update will be posted here via the issue tracker.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

commitMessages:
  commitAuthorName: Recap Time Bot
  commitAuthorEmail: git@recaptime.dev

user-agent: "Upptimebot (https://upptime.js.org; repo: https://github.com/andreijiroh-dev/infra-status)"
