blank_issues_enabled: true
contact_links:
  - name: Meta issue tracker
    url: https://github.com/andreijiroh-dev/personal-launchpad/blob/main/README.md
    about: This issue tracker is reserved for tracking incidents and maintenances. Please check the personal launchpad README for more details.
